const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clean=s=>String(s||'').replace(/\*\*/g,'').replace(/^[-–]\s*/,'').trim();
const statusClass=s=>s.includes('לבדוק')?'status-live':s.includes('קבוע')?'status-fixed':s.includes('גמיש')?'status-flexible':'status-planned';
const maps=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
const imgs={'Nebuta Day Parade':'https://commons.wikimedia.org/wiki/Special:FilePath/Aomori%20Nebuta%20Festival-1.jpg?width=1200','Nebuta Maritime Parade + Fireworks':'https://commons.wikimedia.org/wiki/Special:FilePath/Aomori%20Nebuta%20Festival%20fireworks.jpg?width=1200','Asahidake Ropeway + Sugatami':'https://commons.wikimedia.org/wiki/Special:FilePath/140724%20Asahidake%20Ropeway%20Hokkaido%20Japan04s3.jpg?width=1200'};
const titleMap={'7.8':'Aomori → Shin-Hakodate-Hokuto','8.8':'Hakodate → Lake Toya','9.8':'Lake Toya → Noboribetsu','10.8':'Noboribetsu → Lake Shikotsu → Furano','11.8':'Furano + Biei','12.8':'Furano → Asahidake','13.8':'Asahidake → Otaru → Sapporo','14.8':'Sapporo → New Chitose → Tokyo','15.8':'Tokyo → Narita → Home'};
function nav(current){const ds=['4.8','5.8','6.8','7.8','8.8','9.8','10.8','11.8','12.8','13.8','14.8','15.8'];return `<nav class="topbar"><div class="wrap"><a class="brand" href="index.html">יפן 2026</a><div class="navlinks">${ds.map(d=>`<a href="day-${d.split('.')[0].padStart(2,'0')}.html" ${d===current?'aria-current="page"':''}>${d}</a>`).join('')}</div></div></nav>`}
function parse(md){const lines=md.split(/\r?\n/);let quick=[],acts=[],plan='';let qi=lines.findIndex(x=>x.trim()==='### Quick Summary');if(qi>=0){for(let i=qi+1;i<lines.length;i++){if(lines[i].startsWith('#'))break;if(lines[i].startsWith('- '))quick.push(clean(lines[i].slice(2)))}}for(let i=0;i<lines.length;i++){if(/^# Plan [ABC]/.test(lines[i]))plan=clean(lines[i].slice(2));let m=lines[i].match(/^## (.+?) — (.+)$/);if(!m)continue;let a={time:m[1],name:m[2],status:'מתוכנן',type:'',duration:'',effort:'',tip:'',desc:[],img:'',plan};for(let j=i+1;j<lines.length&&!/^#{1,2} /.test(lines[j]);j++){let s=lines[j].trim();if(!s||s==='---')continue;let z=s.match(/^\*\*סטטוס:\*\*\s*(.+)$/);if(z){a.status=clean(z[1]);continue}z=s.match(/^\*\*סוג:\*\*\s*(.+)$/);if(z){a.type=clean(z[1]);continue}z=s.match(/^\*\*זמן מומלץ:\*\*\s*(.+)$/);if(z){a.duration=clean(z[1]);continue}z=s.match(/^\*\*מאמץ:\*\*\s*(.+)$/);if(z){a.effort=clean(z[1]);continue}z=s.match(/^\*\*תמונה:\*\*\s*(.+)$/);if(z){a.img=clean(z[1]);continue}if(s==='**טיפ:**'){let t=lines[j+1]?.trim();if(t)a.tip=clean(t);continue}if(s.startsWith('### ')||s.startsWith('- ')||s.startsWith('Reservation:')||s.startsWith('Booking:'))continue;if(!s.startsWith('**'))a.desc.push(clean(s))}const transport=/נסיעה|צ'ק|צ׳ק|Hayabusa|AIRDO|Narita Express|Budget|מלון/.test(a.name);a.rich=!transport&&(!!a.img||!!a.tip||a.desc.join(' ').length>120);acts.push(a)}return{quick,acts}}
function planPanel(d){if(!['12.8','13.8'].includes(d))return'';return `<section class="plan-panel"><div class="plan-title"><span>⛅</span><div><small>Asahidake weather decision</small><h2>Plan A / B / C</h2></div></div><div class="plans"><div class="plan recommended"><b>Plan A — מועדף</b><span>ראות טובה ב־12.8: עולים בצהריים.</span></div><div class="plan"><b>Plan B</b><span>ראות גרועה: Ropeway מוקדם ב־13.8 ומקצרים את Otaru.</span></div><div class="plan"><b>Plan C</b><span>גם 13.8 גרוע: מוותרים על הרכבל ושומרים על Otaru + Sapporo.</span></div></div></section>`}
function rich(a){if(!a.rich)return'';let media=imgs[a.name]?`<img class="detail-image" loading="lazy" decoding="async" src="${imgs[a.name]}" alt="${esc(a.img||a.name)}">`:a.img?`<div class="image-placeholder" role="img" aria-label="${esc(a.img)}"><span>📷</span><b>${esc(a.img)}</b></div>`:'';let meta=[a.duration&&`⏱ ${a.duration}`,a.effort&&`🥾 ${a.effort}`,a.type&&`• ${a.type}`].filter(Boolean);return `<details class="activity-detail"><summary>מידע נוסף על המקום <span>＋</span></summary><div class="detail-body">${media}${a.desc.length?`<p class="detail-copy">${esc(a.desc.join(' '))}</p>`:''}${meta.length?`<div class="activity-meta">${meta.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}${a.tip?`<div class="practical-tip"><b>💡 טיפ</b><span>${esc(a.tip)}</span></div>`:''}<a class="maps-cta" target="_blank" rel="noopener" href="${maps(a.name)}">📍 פתח ב-Google Maps</a></div></details>`}
function item(a){return `<article class="timeline-item"><div class="timeline-marker"></div><div class="timeline-main"><div class="timeline-head"><time>${esc(a.time)}</time><span class="status-badge ${statusClass(a.status)}">${esc(a.status)}</span></div><h3>${esc(a.name)}</h3>${a.type?`<div class="compact-type">${esc(a.type)}</div>`:''}${rich(a)}</div></article>`}
function prevNext(d){let ds=['7.8','8.8','9.8','10.8','11.8','12.8','13.8','14.8','15.8'],i=ds.indexOf(d),href=x=>`day-${x.split('.')[0].padStart(2,'0')}.html`;return `<div class="prev-next">${i>0?`<a href="${href(ds[i-1])}">→ היום הקודם <b>${ds[i-1]}</b></a>`:'<a href="index.html">→ כל הימים</a>'}${i<ds.length-1?`<a href="${href(ds[i+1])}"><b>${ds[i+1]}</b> היום הבא ←</a>`:'<a href="index.html">כל הימים ←</a>'}</div>`}
function nowNext(acts,d){let n=new Date();if(n.getMonth()!=7||n.getDate()!=+d.split('.')[0])return'';let mins=n.getHours()*60+n.getMinutes(),timed=acts.map(a=>{let m=a.time.match(/(\d{1,2}):(\d{2})/);return m?{...a,m:+m[1]*60+ +m[2]}:null}).filter(Boolean),cur=timed.filter(a=>a.m<=mins).pop(),nxt=timed.find(a=>a.m>=mins);return `<section class="now-next"><div><small>עכשיו</small><b>${esc(cur?.name||'בין פעילויות')}</b></div><div><small>הבא</small><b>${esc(nxt?.name||'—')}</b><span>${esc(nxt?.time||'')}</span></div></section>`}
async function boot(){let d=document.body.dataset.day;if(!d)return;document.body.insertAdjacentHTML('afterbegin',nav(d));let r=await fetch(`day-data-${d.split('.')[0].padStart(2,'0')}.md`),md=await r.text(),p=parse(md),app=document.getElementById('trip-app');app.innerHTML=`<header class="hero hybrid-hero"><div class="wrap"><p class="eyebrow">7–15 באוגוסט 2026 · ${d}</p><h1>${esc(titleMap[d])}</h1><p>${esc(p.quick.slice(0,2).join(' · '))}</p></div></header><main class="wrap hybrid-main">${prevNext(d)}${nowNext(p.acts,d)}<section class="quick-summary">${p.quick.map(x=>`<div>${esc(x)}</div>`).join('')}</section>${planPanel(d)}<section class="timeline-panel"><div class="section-heading"><div><small>תוכנית היום</small><h2>Timeline</h2></div><span>פתח פרטים רק כשצריך</span></div><div class="timeline">${p.acts.map(item).join('')}</div></section><section class="checklist"><h2>לפני שמסיימים את היום</h2><div>□ טלפונים &nbsp; □ מים &nbsp; □ דלק &nbsp; □ מזג אוויר &nbsp; □ חניה &nbsp; □ כרטיסים/QR &nbsp; □ מזוודות</div></section>${prevNext(d)}</main>`;let a=document.querySelector('.navlinks [aria-current]');a?.scrollIntoView({inline:'center',block:'nearest'})}
document.addEventListener('DOMContentLoaded',boot);
